package com.example.cxf;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-09-13T00:01:48.923+09:00
 * Generated source version: 4.1.3
 *
 */
@WebService(targetNamespace = "http://example.com/cxf", name = "CountryEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface CountryEndpoint {

    @WebMethod
    @RequestWrapper(localName = "getCountry", targetNamespace = "http://example.com/cxf", className = "com.example.cxf.GetCountry")
    @ResponseWrapper(localName = "getCountryResponse", targetNamespace = "http://example.com/cxf", className = "com.example.cxf.GetCountryResponse")
    @WebResult(name = "CountryServiceResult", targetNamespace = "")
    public com.example.cxf.GetCountryResult getCountry(

        @WebParam(name = "CountryServiceParam", targetNamespace = "")
        com.example.cxf.GetCountryParam countryServiceParam
    );
}
