package com.example.cxf;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-09-13T11:41:15.768+09:00
 * Generated source version: 4.1.3
 *
 */
@WebServiceClient(name = "MultipartStoreService",
                  wsdlLocation = "http://localhost:8080/ws/multipart?wsdl",
                  targetNamespace = "http://example.com/cxf")
public class MultipartStoreService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://example.com/cxf", "MultipartStoreService");
    public static final QName MultipartStoreServicePort = new QName("http://example.com/cxf", "MultipartStoreServicePort");
    static {
        URL url = null;
        try {
            url = URI.create("http://localhost:8080/ws/multipart?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MultipartStoreService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws/multipart?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MultipartStoreService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MultipartStoreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultipartStoreService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MultipartStoreService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MultipartStoreService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MultipartStoreService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MultipartEndpoint
     */
    @WebEndpoint(name = "MultipartStoreServicePort")
    public MultipartEndpoint getMultipartStoreServicePort() {
        return super.getPort(MultipartStoreServicePort, MultipartEndpoint.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MultipartEndpoint
     */
    @WebEndpoint(name = "MultipartStoreServicePort")
    public MultipartEndpoint getMultipartStoreServicePort(WebServiceFeature... features) {
        return super.getPort(MultipartStoreServicePort, MultipartEndpoint.class, features);
    }

}
