package com.example.cxf;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.1.3
 * 2025-09-13T11:41:15.621+09:00
 * Generated source version: 4.1.3
 *
 */
@WebService(targetNamespace = "http://example.com/cxf", name = "MultipartEndpoint")
@XmlSeeAlso({ObjectFactory.class})
public interface MultipartEndpoint {

    @WebMethod
    @RequestWrapper(localName = "store", targetNamespace = "http://example.com/cxf", className = "com.example.cxf.Store")
    @ResponseWrapper(localName = "storeResponse", targetNamespace = "http://example.com/cxf", className = "com.example.cxf.StoreResponse")
    public void store(

        @WebParam(name = "ActionId", targetNamespace = "")
        java.lang.String actionId,
        @WebParam(name = "MultipartContent", targetNamespace = "")
        com.example.cxf.MultipartContent multipartContent
    );
}
